import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "../components/Navbar";
import Providers from "@/providers";

const myFont = localFont({
  src: "../../public/font/font.ttf",
  variable: "--font-plus-jakarta-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.className} bg-smoky text-floral bg-gray-100 min-h-screen flex flex-col items-center`}
      >
        <Providers>
        <Navbar />
        {children}
        </Providers>
      </body>
    </html>
  );
}